### ISSUE TITLE
Minor feature request: Custom comment message instead of random text

### ISSUE THREAD

**Issue by leighstillard** [andrewbanchich/shreddit#57]
Hi there, 

Given the current situation at Reddit I want to delete my comment history. However instead of just random text, I'd like to put a protest message in instructing others how to use this application.

I'm a complete novice with Rust but if you point me to the right function I'm happy to figure it out and send a PR.

Thanks!

**Comment by andrewbanchich** [comment]
Hi! I like that idea a lot.

A PR would be great! Otherwise, if you want to start with just getting this working for you, you can clone the repo and replace the lorem Ipsum text [here](https://github.com/andrewbanchich/shreddit/blob/1d0c045211fb7628de6db37acdda56a0b806ea4a/src/things/mod.rs#L47) with your message.

To make this a configuration parameter, you'd modify the Config struct [here](https://github.com/andrewbanchich/shreddit/blob/master/src/cli.rs#LL8C2-L8C2) to include a new field for the custom message.

You'll also want to be sure you've configured it to only edit but not delete.

**Comment by RFBomb** [comment]
I believe the PR I provided should work. I'm not at all familiar with rust, nor do I have a debugger installed for it, so I can't compile it at the moment.  See the PR.

**Comment by andrewbanchich** [comment]
Added in [0.8.0](https://github.com/andrewbanchich/shreddit/releases/tag/v0.8.0). Thanks @RFBomb !
